.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. kore_qt test_kore_qt
clean: FORCE
	$(MAKE) -C .. kore_qt_clean test_kore_qt_clean
check: FORCE
	$(MAKE) -C .. test_kore_qt_check
kore-qt kore-qt.exe: FORCE
	 $(MAKE) -C .. kore_qt
